import { IActions } from '../../interfaces/index';

const actions : IActions = {
    GET_AVERAGE_REQUEST: 'GET_AVERAGE_REQUEST',
    GET_AVERAGE_SUCCESS: 'GET_AVERAGE_SUCCESS',
    GET_QUOTES_REQUEST: 'GET_QUOTES_REQUEST',
    GET_QUOTES_SUCCESS: 'GET_QUOTES_SUCCESS',
    GET_SLIPPAGE_REQUEST: 'GET_SLIPPAGE_REQUEST',
    GET_SLIPPAGE_SUCCESS: 'GET_SLIPPAGE_SUCCESS'
}

export default actions; 